version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp
    container_name: myapp
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db
      - redis
    networks:
      - myapp-network

  db:
    image: mysql:8
    container_name: myapp-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=globalsoft
      - MYSQL_USER=globalsoft
      - MYSQL_PASSWORD=Bjelopoljac123
      - MYSQL_ROOT_PASSWORD=Bjelopoljac123
    volumes:
      - db-data:/var/lib/mysql
      - ./data/globalsoft.sql:/docker-entrypoint-initdb.d/globalsoft.sql
    command: --default-authentication-plugin=mysql_native_password --init-file /docker-entrypoint-initdb.d/globalsoft.sql

    ports:
      - "3306:3306"
    networks:
      - myapp-network

  redis:
    image: redis:alpine
    container_name: myapp-redis
    restart: unless-stopped
    networks:
      - myapp-network

  nginx:
    image: nginx:alpine
    container_name: myapp-nginx
    restart: unless-stopped
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - myapp-network

networks:
  myapp-network:

volumes:
  db-data: